M48
; DRILL file {KiCad (6.0.11)} date Sun Jun  9 14:40:52 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-09T14:40:52-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X2.0742Y-1.7386
X2.2652Y-1.7386
T2
X2.0624Y-1.6193
X2.277Y-1.6193
T3
X1.7323Y-1.3386
X1.7323Y-4.9606
X5.3543Y-1.3386
X5.3543Y-4.9606
T0
M30
